name: Deploy with Secrets

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Inject secrets into config file
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      run: |
        # Criar arquivo temporário para evitar problemas com caracteres especiais
        cp secrets-config.js secrets-config.js.bak
        
        # Substituir os placeholders usando uma abordagem mais robusta
        # Escapa caracteres especiais nas variáveis de ambiente
        ESCAPED_OPENAI_KEY=$(printf '%s\n' "$OPENAI_API_KEY" | sed 's/[[\.*^$()+?{|]/\\&/g')
        ESCAPED_ELEVENLABS_KEY=$(printf '%s\n' "$ELEVENLABS_API_KEY" | sed 's/[[\.*^$()+?{|]/\\&/g')
        
        # Substituir os placeholders no arquivo de configuração
        sed "s/'{{OPENAI_API_KEY}}'/'$ESCAPED_OPENAI_KEY'/g" secrets-config.js.bak > secrets-config.js.tmp
        sed "s/'{{ELEVENLABS_API_KEY}}'/'$ESCAPED_ELEVENLABS_KEY'/g" secrets-config.js.tmp > secrets-config.js
        
        # Limpar arquivos temporários
        rm -f secrets-config.js.bak secrets-config.js.tmp
        
        # Verificar se a substituição foi feita corretamente
        if grep -q "{{" secrets-config.js; then
          echo "Erro: Placeholders não foram substituídos completamente"
          echo "Conteúdo do arquivo após substituição:"
          cat secrets-config.js
          exit 1
        fi
        
        # Verificar se as variáveis de ambiente estão definidas
        if [ -z "$OPENAI_API_KEY" ]; then
          echo "Erro: OPENAI_API_KEY não está definida"
          exit 1
        fi
        
        if [ -z "$ELEVENLABS_API_KEY" ]; then
          echo "Erro: ELEVENLABS_API_KEY não está definida"
          exit 1
        fi
        
        echo "Secrets injetados com sucesso!"
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        keep_files: true