name: Deploy with Secrets

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Inject secrets into config file
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      run: |
        # Substituir os placeholders no arquivo de configuração
        sed -i "s/{{OPENAI_API_KEY}}/$OPENAI_API_KEY/g" secrets-config.js
        sed -i "s/{{ELEVENLABS_API_KEY}}/$ELEVENLABS_API_KEY/g" secrets-config.js
        
        # Verificar se a substituição foi feita corretamente
        if grep -q "{{" secrets-config.js; then
          echo "Erro: Placeholders não foram substituídos completamente"
          exit 1
        fi
        
        echo "Secrets injetados com sucesso!"
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        keep_files: true