name: Deploy with Secrets

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Inject secrets into config file
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
      run: |
        echo "=== Iniciando injeção de secrets ==="
        
        # Verificar se os secrets existem (sem expor valores)
        echo "Verificando secrets..."
        if [ -z "$OPENAI_API_KEY" ]; then
          echo "⚠️ AVISO: OPENAI_API_KEY está vazia ou não definida"
          OPENAI_API_KEY=""
        else
          echo "✅ OPENAI_API_KEY está definida (${#OPENAI_API_KEY} caracteres)"
        fi
        
        if [ -z "$ELEVENLABS_API_KEY" ]; then
          echo "⚠️ AVISO: ELEVENLABS_API_KEY está vazia ou não definida"
          ELEVENLABS_API_KEY=""
        else
          echo "✅ ELEVENLABS_API_KEY está definida (${#ELEVENLABS_API_KEY} caracteres)"
        fi
        
        # Criar backup do arquivo original
        cp secrets-config.js secrets-config.js.original
        
        # Realizar substituições de forma mais segura
        echo "Substituindo placeholders..."
        
        # Usar sed com delimitador diferente para evitar conflitos
        cp secrets-config.js.original secrets-config.js
        
        # Substituir OPENAI_API_KEY
        if [ -n "$OPENAI_API_KEY" ]; then
          sed -i "s|'{{OPENAI_API_KEY}}'|'$OPENAI_API_KEY'|g" secrets-config.js
        else
          sed -i "s|'{{OPENAI_API_KEY}}'|''|g" secrets-config.js
        fi
        
        # Substituir ELEVENLABS_API_KEY
        if [ -n "$ELEVENLABS_API_KEY" ]; then
          sed -i "s|'{{ELEVENLABS_API_KEY}}'|'$ELEVENLABS_API_KEY'|g" secrets-config.js
        else
          sed -i "s|'{{ELEVENLABS_API_KEY}}'|''|g" secrets-config.js
        fi
        
        # Verificar se ainda existem placeholders
        echo "Verificando resultado..."
        if grep -q "{{" secrets-config.js; then
          echo "❌ Erro: Placeholders não foram substituídos completamente"
          echo "Conteúdo atual do arquivo:"
          cat secrets-config.js
          echo ""
          echo "Diferença do original:"
          diff -u secrets-config.js.original secrets-config.js || true
          exit 1
        fi
        
        # Limpar arquivo temporário
        rm -f secrets-config.js.original
        
        echo "✅ Secrets injetados com sucesso!"
        echo "Resultado final (primeiros 15 linhas):"
        head -15 secrets-config.js
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        keep_files: true